title: Automation and Robotics In Reshaping The Workforce
description: A report on disruption innovation in MMS142 (2023) by Group D
show_downloads: true
google_analytics: 
theme: jekyll-theme-cayman

github:
  pdf_url: https://github.com/DaveClemente/mms142-groupd-2023.github.io/blob/52b47ab8a005ec4cf1833f7b61d1d21b400d5766/Final%20Report%20Content.pdf
